[workspace]
members = ["crates/plexo-sdk", "crates/plexo-core", "crates/plexo-next"]
resolver = "2"

[workspace.dependencies]
plexo-core = { path = "crates/plexo-core" }
plexo-sdk = { path = "crates/plexo-sdk" }
