[tasks.depot]
script = '''
depot build --platform linux/amd64 --tag minskylab/plexo-core:v${CARGO_MAKE_CRATE_VERSION} --push .
'''

[tasks.docker]
script = '''
docker build --platform linux/amd64 -t minskylab/plexo-core:v${CARGO_MAKE_CRATE_VERSION} .
docker push minskylab/plexo-core:v${CARGO_MAKE_CRATE_VERSION}
'''
